[project]
name = "small-python-projects"
version = "1.0.6"
description = "small-python-projects"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.5",
    "pytest-mock>=3.14.0",
]
