"""Calculates the sum of the n even-valued terms of the Fibonacci sequence
by considering only the terms whose values do not exceed twelve million.
The Fibonacci sequence:  0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Where F(0) = 0, F(1) = 1 and F(n) = F(n - 1) + F(n - 2) for n > 1.
So, each term greater than 1 is generated by adding the previous two terms.
For example, the 6th element of the sequence is 8.
It uses an iterative programming solution.
Benchmarks function fib_sum with the user created decorator time_it.
"""
__author__ = 'Joan A. Pinol  (japinol)'

from fibonacci.time_it_dec import time_it


@time_it
def fib_sum(limit):
    res = 0
    last_n = 0
    next_n = 1
    while next_n < limit:
        if next_n % 2 == 0:
            res += next_n
        last_n, next_n = next_n, last_n + next_n
    return res


if __name__ == '__main__':
    limit = 12_000_000   # Top limit for the terms' values
    res = fib_sum(limit)
    print(f'fib({limit:}): {res:}')
